const categories = [
  'adventure',
  'fiction',
  'novel',
  'science fiction',
  'mystery',
  'fantasy',
  'history',
  'non fiction',
  'romance',
  'thriller',
  'literature',
  'food',
  'action fiction',
  'drama',
  'graphics novel',
  'self help',
  'autobiography',
  'comic',
  'technology',
  'religion',
  'articles',
  'fairy tale',
  'crime thriller',
  'methodology',
  'textbooks',
  'design',
  'arts',
  'politics',
  'travel',
  'narrative',
];
module.exports = categories;
